/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET DAML SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
import _root_.com.digitalasset.ledger.client.{binding=>$u0020lfdomainapi}
import _root_.com.digitalasset.ledger.api.v1.{value=>$u0020rpcvalue}
package com.knoldus.model {
  package Main {
    final case class TransferOwnership(product: com.knoldus.model.Main.Product, newOwner: ` lfdomainapi`.Primitive.Party) extends ` lfdomainapi`.Template[TransferOwnership] {
      override protected[this] def templateCompanion(implicit ` d` : _root_.scala.Predef.DummyImplicit) = TransferOwnership
    }

    object TransferOwnership extends ` lfdomainapi`.TemplateCompanion[TransferOwnership] with _root_.scala.Function2[com.knoldus.model.Main.Product, ` lfdomainapi`.Primitive.Party, _root_.com.knoldus.model.Main.TransferOwnership] {
      import _root_.scala.language.higherKinds;
      trait view[` C`[_]] extends ` lfdomainapi`.encoding.RecordView[` C`, view] { $u0020view =>
        val product: ` C`[com.knoldus.model.Main.Product];
        val newOwner: ` C`[` lfdomainapi`.Primitive.Party];
        final override def hoist[` D`[_]](` f` : _root_.scalaz.~>[` C`, ` D`]): view[` D`] = {
          final class $anon extends _root_.scala.AnyRef with view[` D`] {
            override val product = ` f`(` view`.product);
            override val newOwner = ` f`(` view`.newOwner)
          };
          new $anon()
        }
      };
      override val id = ` templateId`(packageId = `Package IDs`.Main, moduleName = "Main", entityName = "TransferOwnership");
      final implicit class `TransferOwnership syntax`[+` ExOn`](private val id: ` ExOn`) extends _root_.scala.AnyVal {
        def exerciseArchive(actor: ` lfdomainapi`.Primitive.Party, choiceArgument: com.knoldus.model.DA.Internal.Template.Archive)(implicit ` exOn` : ` lfdomainapi`.encoding.ExerciseOn[` ExOn`, TransferOwnership]): ` lfdomainapi`.Primitive.Update[` lfdomainapi`.Primitive.Unit] = ` exercise`(id, "Archive", _root_.scala.Some(` lfdomainapi`.Value.encode(choiceArgument)));
        def exerciseArchive(actor: ` lfdomainapi`.Primitive.Party)(implicit ` exOn` : ` lfdomainapi`.encoding.ExerciseOn[` ExOn`, TransferOwnership]): ` lfdomainapi`.Primitive.Update[` lfdomainapi`.Primitive.Unit] = exerciseArchive(actor, _root_.com.knoldus.model.DA.Internal.Template.Archive());
        def exerciseAcceptOwnership(actor: ` lfdomainapi`.Primitive.Party, choiceArgument: com.knoldus.model.Main.AcceptOwnership)(implicit ` exOn` : ` lfdomainapi`.encoding.ExerciseOn[` ExOn`, TransferOwnership]): ` lfdomainapi`.Primitive.Update[` lfdomainapi`.Primitive.ContractId[com.knoldus.model.Main.Product]] = ` exercise`(id, "AcceptOwnership", _root_.scala.Some(` lfdomainapi`.Value.encode(choiceArgument)));
        def exerciseAcceptOwnership(actor: ` lfdomainapi`.Primitive.Party)(implicit ` exOn` : ` lfdomainapi`.encoding.ExerciseOn[` ExOn`, TransferOwnership]): ` lfdomainapi`.Primitive.Update[` lfdomainapi`.Primitive.ContractId[com.knoldus.model.Main.Product]] = exerciseAcceptOwnership(actor, _root_.com.knoldus.model.Main.AcceptOwnership())
      };
      override val consumingChoices: Set[` lfdomainapi`.Primitive.ChoiceId] = ` lfdomainapi`.Primitive.ChoiceId.subst(Set("Archive", "AcceptOwnership"));
      override def toNamedArguments(` self` : TransferOwnership) = ` arguments`(scala.Tuple2("product", ` lfdomainapi`.Value.encode(` self`.product)), scala.Tuple2("newOwner", ` lfdomainapi`.Value.encode(` self`.newOwner)));
      override def fromNamedArguments(` r` : ` rpcvalue`.Record) = if (` r`.fields.length.==(2))
        ` r`.fields(0) match {
          case ` rpcvalue`.RecordField((""| "product"), _root_.scala.Some(zv0)) => (` lfdomainapi`.Value.decode[com.knoldus.model.Main.Product](zv0) match {
            case _root_.scala.Some(z0) => (` r`.fields(1) match {
              case ` rpcvalue`.RecordField((""| "newOwner"), _root_.scala.Some(zv1)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Party](zv1) match {
                case _root_.scala.Some(z1) => Some(TransferOwnership(z0, z1))
                case _root_.scala.None => _root_.scala.None
              })
              case _ => _root_.scala.None
            })
            case _root_.scala.None => _root_.scala.None
          })
          case _ => _root_.scala.None
        }
      else
        _root_.scala.None;
      override def fieldEncoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding): view[lte.Field] = {
        object `view ` extends view[lte.Field] {
          val product = lte.field("product", ` lfdomainapi`.encoding.LfEncodable.encoding[com.knoldus.model.Main.Product](lte));
          val newOwner = lte.field("newOwner", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Party](lte))
        };
        `view `
      };
      override def encoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding)(`view `: view[lte.Field]): lte.Out[_root_.com.knoldus.model.Main.TransferOwnership] = {
        val `recordFields `: lte.RecordFields[_root_.com.knoldus.model.Main.TransferOwnership] = lte.RecordFields.xmapN(lte.fields(`view `.product), lte.fields(`view `.newOwner))({
          case scala.Tuple2(product, newOwner) => _root_.com.knoldus.model.Main.TransferOwnership(product, newOwner)
        })({
          case _root_.com.knoldus.model.Main.TransferOwnership(product, newOwner) => scala.Tuple2(product, newOwner)
        });
        lte.record(` dataTypeId`, `recordFields `)
      }
    }
  }
}
